# Generated by Django 2.2.24 on 2025-06-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20190829_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='new_building',
            field=models.BooleanField(choices=[(True, 'Новостройка'), (False, 'Старое здание'), (None, 'Не указано')], default=None, null=True),
        ),
    ]
