# Generated by Django 2.2.24 on 2025-06-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='new_building',
            field=models.BooleanField(choices=[(True, 'Новостройка'), (False, 'Старое здание'), (None, 'Не указано')], default=None, null=True, verbose_name='Новостройка'),
        ),
    ]
