# Generated by Django 2.2.24 on 2025-06-19 18:06

from django.db import migrations


def mark_new_buildings(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.filter(construction_year__gte=2015).update(new_building=True)
    Flat.objects.filter(construction_year__lt=2015).update(new_building=False)


def reverse_mark_new_buildings(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.filter(
        construction_year__gte=2015,
        construction_year__lt=2015
    ).update(new_building=None)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20250619_1946'),
    ]

    operations = [
        migrations.RunPython(mark_new_buildings, reverse_mark_new_buildings)
    ]
