# Generated by Django 2.2.24 on 2025-06-22 16:29

from django.db import migrations
from phonenumbers import parse, is_valid_number


def format_number(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        parsed_pure_phone = parse(flat.owners_phonenumber, 'RU')
        if is_valid_number(parsed_pure_phone):
            flat.owner_pure_phone = parsed_pure_phone
            flat.save()


def clear_pure_phone(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.filter(owner_pure_phone__isnull=False).update(owner_pure_phone='')


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20250622_1929'),
    ]

    operations = [
        migrations.RunPython(format_number, clear_pure_phone)
    ]
