# Generated by Django 2.2.24 on 2025-06-23 17:28

from django.db import migrations


def connect_flats_and_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.all():
        owner = Owner.objects.get(
            owner_name=flat.owner,
            owner_pure_phone=flat.owner_pure_phone
        )
        flat.owners.get_or_create(owner)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20250623_2011'),
    ]

    operations = [
        migrations.RunPython(connect_flats_and_owners)
    ]
